### ISSUE TITLE
Text rendering artifacts on hiDPI

### ISSUE THREAD

**Issue by paulirish** [PolymerElements/paper-menu#29] opened 2015-07-06 19:29 UTC
We're using the menu component here (https://chromedevtools.github.io/debugger-protocol-viewer/) and have a problem:
![image](https://cloud.githubusercontent.com/assets/39191/8530756/c96e7142-23d7-11e5-8b08-ddcbece440d0.png)

screenshot w/ devtools open and two troublesome text styles disabled: http://i.imgur.com/bofejWs.png

We can also reproduce on https://elements.polymer-project.org/elements/paper-menu?active=paper-menu&view=demo:demo/index.html

@kdzwinel

**Comment by kdzwinel** [comment] 2015-07-06 19:48
Some notes:
- it seems to happen only on retina
- we are not using `<paper-item>`'s, we have `<a>`'s directly under `<paper-menu>` (this is taken from [polymer starter kit](https://github.com/PolymerElements/polymer-starter-kit/blob/master/app/index.html#L71))

**Comment by bicknellr** [comment] 2016-01-07 22:35
I can't repro this. Also, given that the screenshot shows two layered copies of the content, which isn't duplicated by either paper-menu or paper-item, my guess is that this was a Chrome rendering bug that has since been fixed. @cdata, can we close this ~~and #23~~?

**Comment by bicknellr** [comment] 2016-01-07 22:37
(The issue 23 mentioned above isn't from this repo.)

**Comment by kdzwinel** [comment] 2016-01-07 22:42
Can't reproduce it either. This did seem like a fixed Chrome rendering bug.

**Closed as completed** 2016-01-27 22:01 UTC
Labels: bug
