### ISSUE TITLE
Link in paper-item inside paper-menu-button

### ISSUE THREAD

**Issue by askibinski** [PolymerElements/paper-menu#22] opened 2015-06-11 11:55 UTC
Search every bit of documentation but I can't find this:

I've got something like the code below. I'm using link tags in combination with app-router routing which works great. The only problem is: I would like to have have the entire paper-menu-item to be clickable with the link tag.

When I use below code, the right page is retrieved when clicking directly on the link tekst itself, but that doesn't create a "selected" state. When I click on the button (just off the text) then the button IS selected but the page isn't retrieved because I didn't click the link...

There must be an easy way to do this right? I mean, I could force this by overriding all the CSS but it seems to me a link in a paper-item in a paper-menu would be a very common thing which should do this automatically or with an attribute or someting?

```
<paper-menu class="list">
  <paper-item icon="home" label="Home" ><a is="pushstate-anchor" href="/">Home</a></paper-item>
  <paper-item icon="polymer" label="Demo"><a is="pushstate-anchor" href="/demo">Demo</a></paper-item>
</paper-menu>
```

(not sure if I posted this right in paper-menu, maybe it belongs in paper-item?)

**Comment by npezza93** [comment] 2015-06-12 18:05
To add to this: If you have that same setup in the drawer of a paper-drawer-panel, on mobile the links don't work.

**Comment by askibinski** [comment] 2015-06-18 15:53
Maybe it is assumed you don't use links (using a href tags) at all, and instead use javascripts events? If that is the case it should be added to the documentation. But still, it seems to me this should work as expected. 
Bytheway, I also posted this question on [stackoverflow](http://stackoverflow.com/questions/30803939/link-in-paper-item-inside-paper-menu-button-polymer-1-0/30918033#30918033) with generated some insight.

**Comment by bicknellr** [comment] 2016-01-07 01:01
This should probably be considered a duplicate of PolymerElements/paper-item#21 (linked above).

**Comment by abdonrd** [comment] 2016-01-07 09:35
Similar discussion here: https://github.com/PolymerElements/paper-button/issues/35#issuecomment-165987461.

**Comment by notwaldorf** [comment] 2016-01-27 22:14
Closing as a dupe of PolymerElements/paper-item#21

**Closed as completed by notwaldorf** 2016-01-27 22:14 UTC
Labels: question
