### ISSUE TITLE
paper-menu jumps to first element after scrolling down then selecting

### ISSUE THREAD

**Issue by japacible** [PolymerElements/paper-menu#17] opened 2015-05-26 15:47 UTC
I have a paper-menu with a list of paper-items. When I scroll down and then click on a paper-item, the menu (and selection) jumps to the top of the menu to the first element.

I first saw this behavior in Chromium with [polymer 0.8-rc.7 and 0.8 elements](https://code.google.com/p/chromium/codesearch#chromium/src/third_party/polymer/v0_8/bower.json), but was able to reproduce this separately.

Here is a [repro](https://github.com/japacible/paper-menu-scroll-repro) for both 0.8 and 0.9, and some [comments](https://codereview.chromium.org/1149983004/) related to [iron-menu-behavior](https://github.com/PolymerElements/iron-menu-behavior/blob/master/iron-menu-behavior.html) and [iron-selectable](https://github.com/PolymerElements/iron-selector/blob/master/iron-selectable.html).

I didn't see this behavior with [polymer 0.5.2 and 0.5.2 elements](https://code.google.com/p/chromium/codesearch#chromium/src/third_party/polymer/bower.json).

Any help would be appreciated, thanks!

**Comment by morethanreal** [comment] 2015-05-26 20:24
This appears to be fixed in the latest 0.9.x release.

**Comment by japacible** [comment] 2015-05-29 18:22
Talked offline, thanks!

**Comment by japacible** [comment] 2015-07-09 17:47
Hey,

We no longer see this on Linux, but we're able to repro this 100% of the time on Mac. This goes for both standalone (see link) and in Chromium. We haven't tested on Windows.

Here's an [updated](https://github.com/japacible/paper-menu-scroll-repro) demo using 1.0 and [video](https://goo.gl/photos/tPDq79FKuyPcHkvD9).

PTAL, thanks!

**Comment by tjsavage** [comment] 2015-08-27 00:02
I'm able to repro this as well on http://output.jsbin.com/bitozu

The problem appears to be when scrolling the menu and clicking on an item when the currently selected item is not in view.

Steps:
- Open the link
- Click on iron-a11y-selector to select it
- Scroll the menu to the bottom
- Click on neon-animation

Result: The menu will jump back up to iron-a11y-selector without selecting neon-animation
Tested on Chrome 44 on Mac.

This looks like it might be a relatively recent regression?

@cdata would you mind taking a look?

**Comment by alessandro-lac** [comment] 2015-09-09 17:59
Same behavior happens to me, tested on Mac (Chrome, Safari and Firefox).

**Comment by japacible** [comment] 2015-09-17 18:59
Hey @tjsavage, any update on this issue? Thanks!

**Comment by notwaldorf** [comment] 2015-09-28 17:23
@tjsavage i definitely saw this happening last week, but I can't repro this today (on all my Mac browsers: Canary or Chrome stable, FF, Safari). Do you have any luck?

**Comment by tjsavage** [comment] 2015-09-28 18:20
I'm unable to repro this now also. Could [this fix in iron-menu-behavior](https://github.com/PolymerElements/iron-menu-behavior/commit/0627737a772ce98256b8dde4a5459d65633ba698) have solved this issue?

**Comment by notwaldorf** [comment] 2015-09-28 18:25
Maybe! Don't look a gift :horse: in the mouth! :)

Should I close this?

**Comment by cdata** [comment] 2015-09-28 18:38
It's possible this was fixed accidentally, but I have seen similar behavior in `paper-tabs` (which implements a common behavior with `paper-menu`), and the noted fix was not a solution for it.

That said, if it can't be reproduced, then I'm not against closing this.

**Comment by tjsavage** [comment] 2015-10-05 17:49
Closing!

**Closed as completed by tjsavage** 2015-10-05 17:49 UTC
Labels: bug, code-yellow
