### ISSUE TITLE
Paper-items with child elements require two clicks to select in Firefox

### ISSUE THREAD

**Issue by mgiuffrida** [PolymerElements/paper-menu#31] opened 2015-07-08 04:01 UTC
In Firefox, I find that I frequently have to double-click paper-items inside a paper-menu if the paper-item has children other than text. The first click activates the element the same way the arrow keys do, but the second click is required to actually select the element.

```
<paper-menu>
  <paper-item>
    Click me once
  </paper-item>
  <paper-item>
    Click me once also
  </paper-item>
  <paper-item>
    <div>You have to click me twice</div>
  </paper-item>
  <paper-item>
    <div>Me too</div>
  </paper-item>
</paper-menu>
```

**Comment by realistschuckle** [comment] 2015-07-17 23:03
This also happens in Safari.

**Comment by cnbuff410** [comment] 2015-07-22 00:08
/sub, happens on Safari and Firefox on my side too.

**Comment by hawkett** [comment] 2015-09-21 20:54
Here's a [JSBin](http://jsbin.com/pizayaciqu/1/edit?html,console,output)

You can see this visually in the demo - to reproduce:
1. **Use Safari!**
2. Click the top menu item - note that selected item has both bold _and_ background highlight
3. Click the bottom menu item
4. Click the top menu item again - note that the top item has the background highlight, but is not bold. The top item must be clicked a second time to reach the correct selected state.

**Comment by notwaldorf** [comment] 2015-09-21 22:12
I think the problem is whether you click on the child or the paper-item itself. It's much easier to reproduce by:
- clicking far away from the text (counts as a selection; this will change the background and bold the text)
- highlighting the text in the item (does not count as a selection; this will change the background, but not bold the text)

Bleh. @cdata

**Comment by notwaldorf** [comment] 2015-09-21 22:14
Also paging in @azakus in case this is a gestures bug

**Comment by hawkett** [comment] 2015-09-21 22:45
It seems like there's some state sticking around after they are first selected. First click on any item works fine. Subsequent attempts to click exhibit problem of requiring two clicks. The background highlight that does appear on the first click appears to be a focus related thing (i.e. the item gets focus, but doesn't select). Is there something going on in the focus handling that prevents the event bubbling perhaps?

**Comment by dfreedm** [comment] 2015-09-21 23:00
It doesn't look like the click event is actually occurring when the selection changes. This leads me to believe there may be something going on with event creation, like what @hawkett suggests.

**Comment by dfreedm** [comment] 2015-09-21 23:41
It's our stylings :( http://jsbin.com/licufenisi/edit?html,css,console,output

**Comment by tehapo** [comment] 2015-09-23 07:11
Found a workaround for this issue by declaring `pointer-events: none` for the child elements.

For example:

``` html
<paper-item>
  <iron-icon icon="home"></iron-icon>
  <span>Home</span>
</paper-item>
```

``` css
paper-item iron-icon,
paper-item span {
    pointer-events: none;
}
```

**Comment by hawkett** [comment] 2015-09-23 19:07
Confirmed! thx @tehapo. Would it make sense for `paper-item` to transparently style its children like this?

**Comment by notwaldorf** [comment] 2015-10-12 19:43
Duplicate of https://github.com/PolymerElements/paper-behaviors/issues/34

**Closed as completed by notwaldorf** 2015-10-12 19:43 UTC

**Comment by Compufreak345** [comment] 2015-11-15 10:44
@notwaldorf PolymerElements/paper-behaviors#34 is marked as fixed, however I still experience this issue with paper-menu. You can see it [here](http://jsbin.com/qojevir/edit?html,console,output) (updated the example from @hawkett to work with the current Polymer version).

**Comment by kritollm** [comment] 2015-11-22 09:41
Experienced exactly the same thing myself, had to click twice in safari. Fortunately style = "pointer-events: none;" fixed the problem:

```
 <a data-route="home" href="/" on-click="onDataRouteClick" style="position:relative">
          <iron-icon style="pointer-events: none;" icon="home"></iron-icon>
          <span style="pointer-events: none;">Home</span>
          <paper-ripple>
          </paper-ripple>
  </a>
```

**Comment by gstroup** [comment] 2015-12-17 20:06
@notwaldorf 
I don't think this issue is fixed.  I just pulled down paper-elements 1.0.5, but I still see the same buggy behavior in Firefox.  When I apply the style "pointer-events: none" in my application as suggested by @kritollm, then the problem is fixed.  Can we reopen this one?

**Comment by notwaldorf** [comment] 2015-12-17 20:20
@gstroup Here is a jsbin with the latest versions of all the elements, and the original code that had the problem. Everything looks fine in Firefox: http://jsbin.com/hayivi/edit?html,output

`paper-elements 1.0.5` is from August, and probably doesn't have all the latest dependencies . In particular, it has a broken `paper-behaviors` import, where the fix exists.

**Comment by gstroup** [comment] 2015-12-17 21:02
@notwaldorf 
Thanks for the info.  I meant to grab 1.0.6, not 1.0.5 version of paper-elements.  Either way, it doesn't include that latest fix for the paper-behaviors import that was just made 2 days ago.  But thank you, now I understand the problem!

**Comment by notwaldorf** [comment] 2015-12-17 21:10
@gstroup Oh, just released `1.0.7` then.

**Comment by gstroup** [comment] 2015-12-17 21:49
@notwaldorf Nice!! Thank you.

**Comment by abdonrd** [comment] 2015-12-22 12:00
@notwaldorf I tried [your last jsbin](http://jsbin.com/hayivi/edit?html,output) in Safari and it doesn't works.
When I click in the text, I always need the second click.

**Comment by flafuente** [comment] 2015-12-27 18:45
@abdonrd same problem here. Any update on this? Thanks.

**Comment by abdonrd** [comment] 2015-12-31 12:38
@flafuente no news for now. :/

**Comment by jakemac53** [comment] 2016-01-13 20:15
@notwaldorf In the [latest jsbin](http://jsbin.com/hayivi/edit?html,output) it looks like there are still issues when you click on the text of the menu items. If you click outside the text then it works fine.

**Comment by bicknellr** [comment] 2016-01-13 22:37
@jakemac53 Just tagged a new release, should be working now. (polygit doesn't update immediately so you'll have to use `//polygit.org/paper-menu+v1.2.2/components/` to see it.)

**Comment by jakemac53** [comment] 2016-01-13 22:56
@bicknellr great seems to be working in FF

**Comment by abdonrd** [comment] 2016-01-14 09:25
Thanks @bicknellr!
