### ISSUE TITLE
Need 1 or 2 clicks, depending on where you click

### ISSUE THREAD

**Issue by kengruven** [PolymerElements/paper-menu#41] opened 2015-08-27 19:29 UTC
I'm playing around with this example (1.1.0): https://elements.polymer-project.org/elements/paper-menu?view=demo:demo/index.html

In Safari 7.1, with the "Standard" menu, sometimes you need to click twice.  If you click in the white area to the right of the word, it moves the gray bar, and also makes the menuitem bold.  If you click on a word itself, it moves the gray bar, but doesn't make it bold.  You have to click a second time to actually activate it.

Other menu types on that page work the same way.  Firefox 40 does not do this: one click is always enough in Firefox.

I don't think this is the same as issue #31, but I'm not sure.

**Comment by cnbuff410** [comment] 2015-08-28 16:40
Same issue in my project

**Comment by pfurio** [comment] 2015-10-01 10:36
Same here in Safari 9.0

**Comment by hawkett** [comment] 2015-10-01 12:02
This is a duplicate of #31, which provides a solution.

**Closed as completed** 2016-01-13 22:38 UTC
